import { useState, useRef } from "react";
import jsPDF from "jspdf";
import { useJobs } from "../hooks/useJobs";
import type { Job } from "../types/job";

interface TailorResult {
  match_score: number;
  tailored_summary: string;
  emphasized_bullets: { original: string; rewritten: string }[];
  skills_to_highlight: string[];
  skill_gaps: string[];
  cover_letter: string;
}

const SCORE_COLOR = (s: number) =>
  s >= 7 ? "text-green-400" : s >= 5 ? "text-yellow-400" : "text-red-400";

function downloadCoverLetterPDF(result: TailorResult, job: Job) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 25;
  const contentW = pageW - margin * 2;
  let y = 20;

  const addText = (
    text: string,
    size: number,
    style: "normal" | "bold" = "normal",
    color: [number, number, number] = [30, 30, 30],
    lineHeight = 6
  ) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentW);
    lines.forEach((line: string) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += lineHeight;
    });
  };

  // Cover letter body
  const lines = result.cover_letter.replace(/\\n/g, "\n").split("\n");
  lines.forEach((line) => {
    if (line.trim() === "") { y += 4; return; }
    addText(line, 11, "normal", [30, 30, 30], 6);
  });

  doc.save(`cover-letter-${job.company.replace(/\s+/g, "-").toLowerCase()}.pdf`);
}

function downloadPDF(result: TailorResult, job: Job) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = 20;

  const addText = (
    text: string,
    size: number,
    style: "normal" | "bold" = "normal",
    color: [number, number, number] = [30, 30, 30],
    lineHeight = 6
  ) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentW);
    lines.forEach((line: string) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += lineHeight;
    });
  };

  const addDivider = () => {
    y += 2;
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageW - margin, y);
    y += 5;
  };

  // Header
  doc.setFillColor(88, 28, 235);
  doc.rect(0, 0, pageW, 14, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("DE Job Hunter — CV Tailor", margin, 9);
  doc.setFont("helvetica", "normal");
  doc.text(`${job.title} @ ${job.company}`, pageW - margin, 9, { align: "right" });
  y = 24;

  // Match score
  addText(`Match Score: ${result.match_score}/10`, 13, "bold", [88, 28, 235]);
  y += 2;

  // ── COVER LETTER ──
  addText("COVER LETTER", 11, "bold", [88, 28, 235]);
  addDivider();
  const lines = result.cover_letter.split("\\n").filter(Boolean);
  lines.forEach((line) => {
    if (line.trim() === "") { y += 3; return; }
    addText(line, 10, "normal", [30, 30, 30], 5.5);
  });
  y += 6;

  // ── PROFESSIONAL SUMMARY ──
  addText("TAILORED PROFESSIONAL SUMMARY", 11, "bold", [88, 28, 235]);
  addDivider();
  addText(result.tailored_summary, 10, "normal", [30, 30, 30], 5.5);
  y += 6;

  // ── REWRITTEN BULLETS ──
  if (y > 220) { doc.addPage(); y = 20; }
  addText("REWRITTEN BULLET POINTS", 11, "bold", [88, 28, 235]);
  addDivider();
  result.emphasized_bullets.forEach((b, i) => {
    addText(`${i + 1}. Original:`, 9, "bold", [100, 100, 100]);
    addText(b.original, 9, "normal", [120, 120, 120], 5);
    y += 1;
    addText("   Rewritten:", 9, "bold", [30, 120, 60]);
    addText(b.rewritten, 9, "normal", [30, 30, 30], 5);
    y += 4;
  });

  // ── SKILLS ──
  if (y > 230) { doc.addPage(); y = 20; }
  addText("SKILLS TO HIGHLIGHT", 11, "bold", [88, 28, 235]);
  addDivider();
  addText(result.skills_to_highlight.join("  •  "), 10, "normal", [30, 30, 30], 5.5);
  y += 4;

  if (result.skill_gaps.length > 0) {
    addText("SKILL GAPS TO BE AWARE OF", 11, "bold", [88, 28, 235]);
    addDivider();
    addText(result.skill_gaps.join("  •  "), 10, "normal", [30, 30, 30], 5.5);
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by DE Job Hunter  •  Page ${i} of ${pageCount}`,
      pageW / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: "center" }
    );
  }

  doc.save(`cover-letter-${job.company.replace(/\s+/g, "-").toLowerCase()}.pdf`);
}

export function CVTailorPage() {
  const { jobs, loading } = useJobs();
  const [selectedJob, setSelectedJob] = useState<Job | null>(null);
  const [result, setResult] = useState<TailorResult | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const coverLetterRef = useRef<HTMLDivElement>(null);

  const eligibleJobs = jobs.filter((j) => j.analysis?.recommendation !== "skip");

  const analyze = async () => {
    if (!selectedJob) return;
    setAnalyzing(true);
    setError(null);
    setResult(null);
    try {
      const resp = await fetch("http://localhost:8000/api/tailor-cv", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          job_title: selectedJob.title,
          company: selectedJob.company,
          description: selectedJob.description,
          location: selectedJob.location,
        }),
      });
      if (!resp.ok) throw new Error(await resp.text());
      setResult(await resp.json());
    } catch (e: any) {
      setError(e.message || "Failed to connect to API server");
    } finally {
      setAnalyzing(false);
    }
  };

  const copyCoverLetter = () => {
    if (!result) return;
    const text = result.cover_letter.replace(/\\n/g, "\n");
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-screen-xl mx-auto px-6 py-6">
      <div className="mb-6">
        <h2 className="text-xl font-bold text-white mb-1">CV Tailor</h2>
        <p className="text-slate-400 text-sm">
          Select a job and Claude will write a full cover letter + tailor your CV for that specific position.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left — Job selector */}
        <div className="flex flex-col gap-4">
          <div className="bg-slate-800 border border-slate-700 rounded-xl p-4">
            <h3 className="text-sm font-semibold text-slate-300 mb-3">Select a Job</h3>
            {loading ? (
              <p className="text-slate-500 text-sm">Loading jobs...</p>
            ) : eligibleJobs.length === 0 ? (
              <p className="text-slate-500 text-sm">No jobs found. Run the pipeline first.</p>
            ) : (
              <div className="flex flex-col gap-2 max-h-80 overflow-y-auto pr-1">
                {eligibleJobs.map((job) => (
                  <button
                    key={job.job_id}
                    onClick={() => { setSelectedJob(job); setResult(null); }}
                    className={`text-left p-3 rounded-lg border transition-colors ${
                      selectedJob?.job_id === job.job_id
                        ? "border-violet-500 bg-violet-500/10"
                        : "border-slate-700 hover:border-slate-500 bg-slate-900/50"
                    }`}
                  >
                    <p className="text-white text-sm font-medium line-clamp-1">{job.title}</p>
                    <p className="text-slate-400 text-xs mt-0.5">{job.company}</p>
                    <div className="flex items-center gap-2 mt-1">
                      <span className={`text-xs font-medium ${
                        job.analysis?.recommendation === "apply" ? "text-green-400" : "text-yellow-400"
                      }`}>
                        {job.analysis?.recommendation}
                      </span>
                      <span className="text-slate-600 text-xs">·</span>
                      <span className="text-slate-500 text-xs">{job.analysis?.tech_match_score}% match</span>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>

          {selectedJob && (
            <div className="bg-slate-800 border border-slate-700 rounded-xl p-4">
              <div className="flex items-start justify-between mb-2">
                <div>
                  <h3 className="text-white font-semibold text-sm">{selectedJob.title}</h3>
                  <p className="text-slate-400 text-xs">{selectedJob.company} · {selectedJob.location}</p>
                </div>
                <a href={selectedJob.url} target="_blank" rel="noopener noreferrer"
                  className="text-violet-400 text-xs hover:text-violet-300 shrink-0">
                  View →
                </a>
              </div>
              <p className="text-slate-400 text-xs line-clamp-3 leading-relaxed mb-4">
                {selectedJob.description?.replace(/<[^>]+>/g, " ").slice(0, 300)}...
              </p>
              <button
                onClick={analyze}
                disabled={analyzing}
                className="w-full bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white text-sm font-medium py-2.5 rounded-lg transition-colors flex items-center justify-center gap-2"
              >
                {analyzing ? (
                  <><span className="animate-spin inline-block">⟳</span> Writing with Claude...</>
                ) : (
                  "✨ Generate Cover Letter & Tailor CV"
                )}
              </button>
            </div>
          )}

          {error && (
            <div className="bg-red-500/10 border border-red-500/30 text-red-400 text-xs rounded-xl p-3">
              {error}
              <p className="mt-1 text-slate-500">
                Start the API server: <code className="bg-slate-800 px-1 rounded">python3 api_server.py</code>
              </p>
            </div>
          )}
        </div>

        {/* Right — Results */}
        <div>
          {!result && !analyzing && (
            <div className="bg-slate-800/50 border border-dashed border-slate-700 rounded-xl p-8 flex flex-col items-center justify-center min-h-64 text-center">
              <p className="text-4xl mb-3">📄</p>
              <p className="text-slate-400 text-sm">Select a job and click Generate</p>
              <p className="text-slate-600 text-xs mt-1">Claude will write a full cover letter and tailor your CV</p>
            </div>
          )}

          {analyzing && (
            <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-8 flex flex-col items-center justify-center min-h-64 text-center">
              <p className="text-4xl mb-3 animate-pulse">🤖</p>
              <p className="text-slate-400 text-sm">Writing your cover letter...</p>
              <p className="text-slate-600 text-xs mt-1">This may take 10-15 seconds</p>
            </div>
          )}

          {result && selectedJob && (
            <div className="flex flex-col gap-4">
              {/* Match score + download */}
              <div className="bg-slate-800 border border-slate-700 rounded-xl p-4 flex items-center gap-4">
                <div className="text-center shrink-0">
                  <p className={`text-3xl font-bold ${SCORE_COLOR(result.match_score)}`}>
                    {result.match_score}/10
                  </p>
                  <p className="text-slate-400 text-xs mt-0.5">Match</p>
                </div>
                <div className="flex-1">
                  <div className="h-2 bg-slate-700 rounded-full overflow-hidden">
                    <div className="h-full bg-violet-500 rounded-full transition-all"
                      style={{ width: `${result.match_score * 10}%` }} />
                  </div>
                </div>
                <button
                  onClick={() => downloadPDF(result, selectedJob)}
                  className="shrink-0 flex items-center gap-2 bg-green-600 hover:bg-green-500 text-white text-xs font-medium px-4 py-2 rounded-lg transition-colors"
                >
                  ⬇ Download PDF
                </button>
              </div>

              {/* Cover Letter */}
              <div className="bg-slate-800 border border-violet-500/40 rounded-xl p-5" ref={coverLetterRef}>
                <div className="flex items-center justify-between mb-3">
                  <h4 className="text-sm font-semibold text-violet-400 uppercase tracking-wider">
                    Cover Letter
                  </h4>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={copyCoverLetter}
                      className="text-xs text-slate-400 hover:text-white bg-slate-700 hover:bg-slate-600 px-3 py-1 rounded-lg transition-colors"
                    >
                      {copied ? "✓ Copied!" : "Copy"}
                    </button>
                    <button
                      onClick={() => downloadCoverLetterPDF(result, selectedJob)}
                      className="text-xs text-white bg-green-600 hover:bg-green-500 px-3 py-1 rounded-lg transition-colors"
                    >
                      ⬇ PDF
                    </button>
                  </div>
                </div>
                <div className="text-slate-200 text-sm leading-relaxed whitespace-pre-line font-serif">
                  {result.cover_letter.replace(/\\n/g, "\n")}
                </div>
              </div>

              {/* Professional Summary */}
              <div className="bg-slate-800 border border-slate-700 rounded-xl p-4">
                <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2">
                  Tailored Professional Summary
                </h4>
                <p className="text-slate-300 text-sm leading-relaxed">{result.tailored_summary}</p>
              </div>

              {/* Rewritten bullets */}
              <div className="bg-slate-800 border border-slate-700 rounded-xl p-4">
                <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider mb-3">
                  Rewritten Bullet Points
                </h4>
                <div className="flex flex-col gap-4">
                  {result.emphasized_bullets.map((b, i) => (
                    <div key={i} className="flex flex-col gap-1.5 pb-3 border-b border-slate-700 last:border-0 last:pb-0">
                      <p className="text-slate-500 text-xs line-through leading-relaxed">{b.original}</p>
                      <p className="text-green-400 text-xs leading-relaxed">→ {b.rewritten}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Skills */}
              <div className="grid grid-cols-2 gap-3">
                <div className="bg-slate-800 border border-slate-700 rounded-xl p-4">
                  <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2">Highlight</h4>
                  <div className="flex flex-wrap gap-1">
                    {result.skills_to_highlight.map((s) => (
                      <span key={s} className="bg-green-500/10 text-green-400 border border-green-500/20 text-xs px-2 py-0.5 rounded-full">{s}</span>
                    ))}
                  </div>
                </div>
                <div className="bg-slate-800 border border-slate-700 rounded-xl p-4">
                  <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2">Skill Gaps</h4>
                  <div className="flex flex-wrap gap-1">
                    {result.skill_gaps.length > 0 ? result.skill_gaps.map((s) => (
                      <span key={s} className="bg-red-500/10 text-red-400 border border-red-500/20 text-xs px-2 py-0.5 rounded-full">{s}</span>
                    )) : (
                      <span className="text-slate-500 text-xs">No major gaps!</span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
